<?php

use Symfony\Component\Yaml\Yaml;

return [
    /**
     * Aliases are replaced in the @apidoc annotation path
     */
    'aliases' => [
        '@' => app_path(),
    ],

    /**
     * This template is applied when writing the toplevel open-api.yml
     */
    'template' => Yaml::parseFile(resource_path('open-api.tpl.yaml')),

    /**
     * This template is applied when writing each paths.{path}.{method} entru
     */
    'route-template' => Yaml::parseFile(resource_path('route.tpl.yaml')),

    /**
     * Do not generate open-api entries for head routes
     * head routes are automatically generated by laravel when a get route is added so if you don't actually use them
     * you can set to ignore them here
     */
    'ignore-head-routes' => true,
];
